apiVersion: apps/v1
kind: Deployment
metadata:
  name: rajtharan-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rajtharan
  template:
    metadata:
      labels:
        app: rajtharan
    spec:
      containers:
      - name: rajtharan
        image: rajtharan1125.azurecr.io/rajtharan:v1
        ports:
        - containerPort: 8080
